service: serverless-url-shortener

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: default
  httpApi:
    cors: true

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  UrlsTable: urls

functions:
  getUrl:
    handler: lambdas/getUrl.handler
    events:
      - httpApi:
          path: /urls/{id}
          method: get

resources:
  Resources:
    UrlsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.UrlsTable}
        AttributeDefinitions: # only used for keySchema keys
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
