service: serverless-url-shortener

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: default
  region: us-east-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
  httpApi:
    cors: true

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  getUrl:
    handler: lambdas/endpoints/v1/urls/get.handler
    events:
      - httpApi:
          path: /v1/urls/{id}
          method: get
  createCode:
    handler: lambdas/endpoints/v1/codes/create.handler
    events:
      - httpApi:
          path: /v1/codes
          method: post

resources:
  Resources:
    UrlsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions: # only used for keySchema keys
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
