service: serverless-url-shortener

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: default
  httpApi:
    cors: true

functions:
  getUrl:
    handler: lambdas/getUrl.handler
    events:
      - httpApi:
          path: /urls/{id}
          method: get
