service: serverless-url-shortener

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: default
  region: us-east-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
    SQS_URL: ${construct:urls-queue.queueUrl}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
  httpApi:
    cors: true
  apiGateway:
    apiKeys:
      - free:
          - ${sls:stage}-FreePlanKey
      - basic:
          - ${sls:stage}-BasicPlanKey
      - premium:
          - ${sls:stage}-PremiumPlanKey
    usagePlan:
      - free:
          quota:
            limit: 1000
            period: MONTH
          throttle:
            burstLimit: 200
            rateLimit: 100
      - basic:
          quota:
            limit: 2000
            period: MONTH
          throttle:
            burstLimit: 400
            rateLimit: 200
      - premium:
          quota:
            limit: 10000
            period: MONTH
          throttle:
            burstLimit: 2000
            rateLimit: 1000

plugins:
  - serverless-webpack
  - serverless-lift

package:
  individually: true

functions:
  getUrl:
    handler: lambdas/endpoints/v1/urls/get.handler
    events:
      - http:
          path: /v1/urls/{id}
          method: get
          cors: true
  createCode:
    handler: lambdas/endpoints/v1/codes/create.handler
    events:
      - http:
          path: /v1/codes
          method: post
          private: true
          cors: true
  enqueueUrl:
    handler: lambdas/endpoints/v1/urls/enqueue.handler
    events:
      - http:
          path: /v1/urls/enqueue
          method: post
          private: true
          cors: true

constructs:
  urls-queue:
    type: queue
    worker:
      handler: lambdas/workers/codes/create.handler

resources:
  Resources:
    UrlsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions: # only used for keySchema keys
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
