name: Deploy main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Serverless App Deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm i
      - name: serverless deploy --verbose --stage production
        uses: serverless/github-action@v3.2
        with:
          args: |
            -c "serverless plugin install -n serverless-webpack && \
                serverless plugin install -n serverless-lift && \
                npm install --save @aws-sdk/client-sqs && \
                npm install --save @aws-sdk/lib-dynamodb && \
                npm install --save @aws-sdk/client-dynamodb && \
                serverless deploy"
          entrypoint: /bin/sh
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
